### ISSUE TITLE
A Runtime Error

### ISSUE THREAD

**Issue by activemy** [PeterWang512/FALdetector#4]
When I use the command in readme,I got this:
Traceback (most recent call last):
  File "local_detector.py", line 58, in <module>
    faces = face_detection(img_path, verbose=False)
  File "/root/Code/FALdetector/utils/tools.py", line 113, in face_detection
    dets = cnn_face_detector(im, 0)
RuntimeError: Expected writable numpy.ndarray with shape set.

It looks like blib throw this error ,and i’m Not familiar with blib.
I try to use cv2.imread load image,it works some time,but not always,I can’t fix it.
Hope Help,thx.

**Comment by PeterWang512** [comment]
Have you tried adding: `im.setflags(write=True)` right above line 113 in `utils/tools.py`?
It seems like for some reason your array is not writable, so adding this line might be able to help.

**Comment by activemy** [comment]
It works.Thank you.
