### ISSUE TITLE
Can't download drn models.

### ISSUE THREAD

**Issue by zheolls** [PeterWang512/FALdetector#6]
The website can't download files with error 403.
I upgraded the drn.py/url to http://dl.yf.io/drn/, noticing that the author has deleted the drn-c* models.

**Comment by rocknamx8** [comment]
I also get in this trouble.

**Comment by PeterWang512** [comment]
Committed a change that prevents the code from loading the drn-c* models pretrained on ImageNet. Hopefully this will solve this issue.
